module.exports = {
  apps: [
    {
      name: 'web',
      cwd: './apps/web',
      script: 'bun',
      args: 'run start',
      env: { NODE_ENV: 'production', PORT: '3000' },
      max_memory_restart: '600M',
      max_restarts: 10,
      time: true,
    },
    {
      name: 'server',
      cwd: './apps/server',
      script: 'bun',
      args: 'index.ts',
      env: { NODE_ENV: 'production', SERVER_PORT: '8080' },
      max_memory_restart: '400M',
      max_restarts: 10,
      time: true,
    },
    {
      name: 'mirror',
      cwd: './apps/mirror',
      script: 'bun',
      args: 'index.ts',
      env: { NODE_ENV: 'production' },
      max_memory_restart: '300M',
      max_restarts: 10,
      time: true,
    },
    {
      name: 'hedger',
      cwd: './apps/hedger',
      script: 'bun',
      args: 'index.ts',
      env: { NODE_ENV: 'production', HEDGER_HEALTH_PORT: '4001' },
      max_memory_restart: '500M',
      max_restarts: 10,
      time: true,
    },
  ],
};
